@startchen
left to right direction

entity Аптека {
    название
    электронная_почта
    пароль/'хэш пароля'/
    адрес
    статус /'подтверждённая или нет'/
}
entity Сотрудник {
    фамилия
    имя
    отчество
    электронная_почта
    пароль/'хэш пароля'/
    роль /'оператор или администратор'/
}
entity Заказ{
    номер
    статус/'подтверждён или находится на рассмострении'/
}

/'
непосредственно сами лекарства, которые человек приобретает в аптеке.
'/
entity Лекарственный_Препарат{
    название
    лекарственная_форма /'(мазь,крем,таблетки)Как назвать?'/
    дозировка
    количество
    код_маркировки/'Система "Честный Знак'/
    номер_партии
    дата_изготовления
    срок_годности
    статус/'свободный, просрочен, в заказе'/
    рецептурный_ли
    изготовитель
}

/'
это вещества или их комбинации, из которых состоят препараты.
'/
entity Лекарственное_Средство{
    название
    вещества
}

relationship Сделала {
}
relationship Производится_В_Виде {
}

Аптека -1- Сделала
Сделала -N- Заказ

Лекарственное_Средство -1- Производится_В_Виде
Производится_В_Виде -N- Лекарственный_Препарат



@endchen
