@startuml
left to right direction

rectangle "Внешние пользователи"{
actor Аптека as pharmacy
}
rectangle "Сотрудники склада" {
  actor Оператор as operator
  actor Администратор as admin
  operator <|- admin
}


rectangle "Информационная система заказов" {

pharmacy --> (Зарегистрироваться)
pharmacy --> (Войти в систему)
pharmacy --> (Просмотреть доступные лекарства)
pharmacy --> (Сделать заказ лекарств)
pharmacy --> (Посмотреть свои заказы)
}

rectangle "Информационная система склада" {

admin --> (Управлять сотрудниками) 
(Управлять сотрудниками) .> (Добавить сотрудника) : <<extend>>
(Управлять сотрудниками) .> (Изменить сотрудника) : <<extend>>
(Управлять сотрудниками) .> (Удалить сотрудника) : <<extend>>

admin --> (Управлять аптеками)
(Управлять аптеками) .> (Добавить аптеку) : <<extend>>
(Управлять аптеками) .> (Изменить аптеку) : <<extend>>
(Управлять аптеками) .> (Удалить аптеку) : <<extend>>

operator --> (Управлять лекарствами)
(Управлять лекарствами) .> (Добавить лекарство/партию) : <<extend>>
(Управлять лекарствами) .> (Изменить лекарство) : <<extend>>
(Управлять лекарствами) .> (Списать просроченное лекарство) : <<extend>>

operator --> (Управлять заказами)
(Управлять заказами) .> (Подтвердить заказ) : <<extend>>
(Управлять заказами) .> (Отменить заказ) : <<extend>>

}

@enduml
